In [2]:
from datasets import load_dataset
import numpy as np
import torch
from torch.utils.data import Dataset
import torch.nn as nn
from torch.utils.data import BatchSampler, Sampler, DataLoader

In [4]:
ds = load_dataset("csv", data_files={"train": "train.csv", "test": "test.csv", "sample_submissions": "sample_submission.csv"}
)

In [5]:
ds.set_format("pandas")

In [6]:
goods_image_vectors = np.load("D:\jup\goods_image_vectors\goods_image_vectors\embed_deperson.npy")
goods_image_items = np.load("D:\jup\goods_image_vectors\goods_image_vectors\items_deperson.npy")
goods_tittle_vectors = np.load("D:\jup\goods_title_vectors\goods_title_vectors\embed_deperson.npy")
goods_tittle_items = np.load("D:\jup\goods_title_vectors\goods_title_vectors\items_deperson.npy")
offer_image_vectors = np.load("D:\jup\offer_image_vectors\offer_image_vectors\embed_deperson.npy")
offer_image_items = np.load("D:\jup\offer_image_vectors\offer_image_vectors\items_deperson.npy")
offer_tittle_vectors = np.load("D:\jup\offer_title_vectors\offer_title_vectors\embed_deperson.npy")
offer_tittle_items = np.load("D:\jup\offer_title_vectors\offer_title_vectors\items_deperson.npy")

print(len(goods_image_vectors), len(goods_image_items))

<>:1: SyntaxWarning: invalid escape sequence '\j'
<>:2: SyntaxWarning: invalid escape sequence '\j'
<>:3: SyntaxWarning: invalid escape sequence '\j'
<>:4: SyntaxWarning: invalid escape sequence '\j'
<>:5: SyntaxWarning: invalid escape sequence '\j'
<>:6: SyntaxWarning: invalid escape sequence '\j'
<>:7: SyntaxWarning: invalid escape sequence '\j'
<>:8: SyntaxWarning: invalid escape sequence '\j'
<>:1: SyntaxWarning: invalid escape sequence '\j'
<>:2: SyntaxWarning: invalid escape sequence '\j'
<>:3: SyntaxWarning: invalid escape sequence '\j'
<>:4: SyntaxWarning: invalid escape sequence '\j'
<>:5: SyntaxWarning: invalid escape sequence '\j'
<>:6: SyntaxWarning: invalid escape sequence '\j'
<>:7: SyntaxWarning: invalid escape sequence '\j'
<>:8: SyntaxWarning: invalid escape sequence '\j'
C:\Users\volko\AppData\Local\Temp\ipykernel_11912\1839093641.py:1: SyntaxWarning: invalid escape sequence '\j'
  goods_image_vectors = np.load("D:\jup\goods_image_vectors\goods_image_vectors\embed_deperson.npy")
C:\Users\volko\AppData\Local\Temp\ipykernel_11912\1839093641.py:2: SyntaxWarning: invalid escape sequence '\j'
  goods_image_items = np.load("D:\jup\goods_image_vectors\goods_image_vectors\items_deperson.npy")
C:\Users\volko\AppData\Local\Temp\ipykernel_11912\1839093641.py:3: SyntaxWarning: invalid escape sequence '\j'
  goods_tittle_vectors = np.load("D:\jup\goods_title_vectors\goods_title_vectors\embed_deperson.npy")
C:\Users\volko\AppData\Local\Temp\ipykernel_11912\1839093641.py:4: SyntaxWarning: invalid escape sequence '\j'
  goods_tittle_items = np.load("D:\jup\goods_title_vectors\goods_title_vectors\items_deperson.npy")
C:\Users\volko\AppData\Local\Temp\ipykernel_11912\1839093641.py:5: SyntaxWarning: invalid escape sequence '\j'
  offer_image_vectors = np.load("D:\jup\offer_image_vectors\offer_image_vectors\embed_deperson.npy")
C:\Users\volko\AppData\Local\Temp\ipykernel_11912\1839093641.py:6: SyntaxWarning: invalid escape sequence '\j'
  offer_image_items = np.load("D:\jup\offer_image_vectors\offer_image_vectors\items_deperson.npy")
C:\Users\volko\AppData\Local\Temp\ipykernel_11912\1839093641.py:7: SyntaxWarning: invalid escape sequence '\j'
  offer_tittle_vectors = np.load("D:\jup\offer_title_vectors\offer_title_vectors\embed_deperson.npy")
C:\Users\volko\AppData\Local\Temp\ipykernel_11912\1839093641.py:8: SyntaxWarning: invalid escape sequence '\j'
  offer_tittle_items = np.load("D:\jup\offer_title_vectors\offer_title_vectors\items_deperson.npy")

317707 317707

In [7]:
print(len(offer_image_vectors), len(offer_image_items))

457586 457586

In [8]:
goods_image_items = list(map(str, goods_image_items))
goods_tittle_items = list(map(str, goods_tittle_items))
offer_image_items = list(map(str, offer_image_items))
offer_tittle_items = list(map(str, offer_tittle_items))

In [9]:

goods_image = dict(zip(goods_image_items, torch.from_numpy(goods_image_vectors)))
goods_tittle = dict(zip(goods_tittle_items, torch.from_numpy(goods_tittle_vectors)))
offers_image = dict(zip(offer_image_items, torch.from_numpy(offer_image_vectors)))
offers_tittle = dict(zip(offer_tittle_items, torch.from_numpy(offer_tittle_vectors)))

In [10]:
sets  = (
    set(goods_image.keys()) & set(goods_tittle.keys()) & set(offers_image.keys()) 
    & set(offers_tittle.keys())
)

In [11]:
len(sets)

123515

In [12]:
goods_image_s, goods_tittle_s, offers_image_s, offers_tittle_s = {}, {}, {}, {}

for k in sets:
    goods_image_s[k] = goods_image[k]
    goods_tittle_s[k] = goods_tittle[k]
    offers_image_s[k] = offers_image[k]
    offers_tittle_s[k] = offers_tittle[k]

In [13]:
len(goods_image_s)

123515

In [14]:
df = ds["train"].to_pandas()
dt = ds["test"].to_pandas()

In [15]:
df = df[df["target"]==1].dropna()

In [16]:
s = (df["goods_price"]- df["offer_price"]).abs().median()

In [17]:
df_wo_str = df.drop(columns="id")

In [18]:
df_wo_str.corr()

,offer_depersanalised,goods_depersanalised,sum_length,attrs+title_score,offer_price,goods_price,goods_category_id,target
offer_depersanalised,1.000000,-0.001288,0.084979,0.091408,0.073801,0.029088,-0.015824,NaN
goods_depersanalised,-0.001288,1.000000,-0.032544,0.080287,-0.012044,0.069469,-0.013550,NaN
sum_length,0.084979,-0.032544,1.000000,0.150886,0.088058,0.291534,0.137780,NaN
attrs+title_score,0.091408,0.080287,0.150886,1.000000,0.004807,0.008850,-0.019941,NaN
offer_price,0.073801,-0.012044,0.088058,0.004807,1.000000,0.068414,0.041237,NaN
goods_price,0.029088,0.069469,0.291534,0.008850,0.068414,1.000000,0.131366,NaN
goods_category_id,-0.015824,-0.013550,0.137780,-0.019941,0.041237,0.131366,1.000000,NaN
target,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
df.head()

,offer_depersanalised,goods_depersanalised,sum_length,attrs+title_score,offer_price,goods_price,goods_category_id,target,id
254,118303,832186,54,0.262939,8520,8320.0,19.0,1,118303$832186
374,118088,832202,54,0.258545,6270,6120.0,19.0,1,118088$832202
413,118118,839035,54,0.251221,6790,6620.0,19.0,1,118118$839035
542,21953,843075,55,0.166870,131234,113099.0,8.0,1,21953$843075
1490,272114,860295,60,0.196411,112666,89455.0,8.0,1,272114$860295

In [20]:
dt["price_different"] = dt["goods_price"]-dt["offer_price"].abs()

In [21]:
dt.sort_values(by="price_different", ascending=False)

,offer_depersanalised,goods_depersanalised,sum_length,attrs+title_score,offer_price,goods_price,goods_category_id,target,id,price_different
271688,424740,41073,795,0.001225,6162,1.638016e+09,6.000000e+00,NaN,424740$41073,1.638010e+09
311160,423333,842619,1040,0.869141,22560,1.638016e+09,6.000000e+00,NaN,423333$842619,1.637994e+09
267874,423333,41038,776,0.000038,22560,1.638016e+09,6.000000e+00,NaN,423333$41038,1.637994e+09
303740,424712,1560422,983,0.864258,20690,1.560016e+09,6.000000e+00,NaN,424712$1560422,1.559995e+09
345304,421937,41163,1380,0.051178,15700,8.120822e+07,4.000000e+00,NaN,421937$41163,8.119252e+07
...,...,...,...,...,...,...,...,...,...,...
363807,24514,209319,3949,0.001567,2000,NaN,2.463685e+15,NaN,24514$209319,NaN
363825,314579,130243,4681,0.000061,4008,NaN,2.463685e+15,NaN,314579$130243,NaN
363827,208075,303414,4918,0.000053,678,NaN,2.463685e+15,NaN,208075$303414,NaN
363829,514821,130172,4955,0.000035,2238,NaN,2.463685e+15,NaN,514821$130172,NaN
363830,122775,310950,5061,0.000036,804,NaN,2.463685e+15,NaN,122775$310950,NaN

In [22]:
print(type(new_df))

NameError: name 'new_df' is not defined

In [23]:
df['price_different'] = abs(df['offer_price'] - df['goods_price'])
new_df = df.drop(columns=['sum_length', 'offer_price', 'goods_price'])
new_df = new_df.rename(columns={'price_different':'price_difference'})

In [24]:
new_df.head()

,offer_depersanalised,goods_depersanalised,attrs+title_score,goods_category_id,target,id,price_difference
254,118303,832186,0.262939,19.0,1,118303$832186,200.0
374,118088,832202,0.258545,19.0,1,118088$832202,150.0
413,118118,839035,0.251221,19.0,1,118118$839035,170.0
542,21953,843075,0.166870,8.0,1,21953$843075,18135.0
1490,272114,860295,0.196411,8.0,1,272114$860295,23211.0

In [25]:
new_df['pair']= tuple(zip(df['offer_depersanalised'], df['goods_depersanalised'], df['target']))
new_df.head()

,offer_depersanalised,goods_depersanalised,attrs+title_score,goods_category_id,target,id,price_difference,pair
254,118303,832186,0.262939,19.0,1,118303$832186,200.0,"(118303, 832186, 1)"
374,118088,832202,0.258545,19.0,1,118088$832202,150.0,"(118088, 832202, 1)"
413,118118,839035,0.251221,19.0,1,118118$839035,170.0,"(118118, 839035, 1)"
542,21953,843075,0.166870,8.0,1,21953$843075,18135.0,"(21953, 843075, 1)"
1490,272114,860295,0.196411,8.0,1,272114$860295,23211.0,"(272114, 860295, 1)"

In [26]:
ks = goods_image_s.keys()

mask = [str(a[0]) in ks and str(a[1]) in ks for a in new_df['pair'].to_list()]
new_df = new_df[mask].reset_index(drop=True)
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25298 entries, 0 to 25297
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   offer_depersanalised  25298 non-null  int64
 1   goods_depersanalised  25298 non-null  int64
 2   attrs+title_score     25298 non-null  float64
 3   goods_category_id     25298 non-null  float64
 4   target                25298 non-null  int64
 5   id                    25298 non-null  object
 6   price_difference      25298 non-null  float64
 7   pair                  25298 non-null  object
dtypes: float64(3), int64(3), object(2)
memory usage: 1.5+ MB

In [27]:
new_df = new_df.drop_duplicates(subset='pair', keep='first')

In [28]:
len(new_df['pair'])

25053

In [39]:
class data(Dataset):
    def __init__(self, table, img_g, img_o, tittle_g, tittle_o, pairs):
        self.table = table
        self.img_g = img_g
        self.img_o = img_o
        self.tittle_o = tittle_o
        self.tittle_g = tittle_g
        self.pairs = pairs

    def __getitem__(self, i):
        pair_ = self.pairs[i]
        id_o, id_g, y = pair_

        return {
            'img_goods':self.img_g[str(id_g)],
            'img_offers': self.img_o[str(id_o)],
            'tittle_goods': self.tittle_g[str(id_g)],
            'tittle_offers': self.tittle_o[str(id_o)],
            'difference': torch.tensor(self.table.loc[self.table['pair']== pair_, 'price_difference'].item(), dtype=torch.float32),
            'category': self.table.loc[self.table['pair']== pair_, 'goods_category_id'].item(),
            'y': y            
        }


    
    def __len__(self):
        return len(self.pairs)

In [30]:
import random

In [40]:
class SortByCategory(Sampler):
    def __init__(self, dataset, batch_size=32):
        self.dataset = dataset
        self.batch_size = batch_size

        self.ind_cat = {}
        for idx in range(len(dataset)):
            cat = dataset[idx]['category']
            if cat not in self.ind_cat:
                self.ind_cat[cat] = []
            self.ind_cat[cat].append(idx)

        self.batches = []
        for cat, ind in self.ind_cat.items():
            random.shuffle(ind)
            for i in range(0, len(ind), batch_size):
                self.batches.append(ind[i:i+batch_size])



        random.shuffle(self.batches)

        def __iter__(self):
            for batch in self.batches:
                yield batch

        def __len__(self):
            return len(self.batches)

In [135]:
dataset = data(new_df, goods_image_s, offers_image_s, goods_tittle_s, offers_tittle_s, new_df['pair'].to_list())

In [136]:
dataset.info()

AttributeError: 'data' object has no attribute 'info'

In [137]:
batch_sampler = SortByCategory(dataset=dataset, batch_size=32)

In [138]:
dataloader = DataLoader(dataset, batch_sampler=batch_sampler)

In [48]:
dataset[12]

{'img_goods': tensor([ 0.1014, -0.8819,  0.7784,  2.0945,  0.6039,  1.0421,  1.1884,  4.4960,
          0.8402,  0.4606,  1.0210, -0.9865,  0.3255,  3.1118,  1.4009,  0.9078,
         -1.1150,  0.2217, -3.3405, -2.5588,  1.9875, -0.4487, -1.7720,  2.8729,
          0.7391, -0.3400, -1.3706,  0.1450,  1.3011,  2.0324,  0.9299, -0.6019,
         -0.5901, -0.6243,  0.5309,  1.9642, -0.9100,  1.7781,  0.7793,  0.7115,
         -1.3458,  1.5033,  2.7636, -0.3496,  0.9722, -1.0996,  1.6362, -1.7350,
         -1.0631,  1.3505, -1.6814,  0.8571,  0.5529, -0.0457,  2.1859, -0.0758,
          0.2737,  0.1896,  2.8719, -1.7859, -0.9248,  2.4122,  0.5412,  0.9646,
          2.7235, -1.4182,  0.4996,  2.1340,  1.0561,  1.7337, -0.0592, -0.1529,
         -1.7685,  0.8766, -0.0453, -0.4567, -2.0834,  0.9449, -1.0032,  3.6631,
         -0.6336,  2.4191, -0.7582,  0.5572, -0.0563,  0.9878,  0.0133,  1.4373,
          2.0424, -0.9612, -1.7577,  0.9195,  1.9177,  1.9461, -0.5334,  1.2973,
          0.4440, -1.2411,  1.7519,  2.7456,  0.1260, -0.8651,  0.7519, -0.7964,
          1.2998, -2.7631,  1.4000, -1.2023,  0.1661,  0.8499, -1.1238,  0.7204,
         -0.5730, -0.0352,  0.6053, -2.6099, -1.1983,  3.1439, -0.7927, -2.6071,
         -1.0941,  0.2192,  0.2189, -1.6198, -0.8986,  2.5398, -0.2366,  1.9088,
         -1.6509,  1.5580,  1.8785, -1.5125, -1.2004,  3.2688,  0.3551,  1.0515,
         -1.9216,  0.9107,  1.1373, -1.5943, -3.3096,  0.3341,  0.0741, -0.7758,
          1.5787,  1.1128,  0.3647, -0.7918, -0.6485, -0.8358, -1.9824,  0.5146,
         -1.6519,  1.6602,  0.5471,  2.1407, -0.7236, -2.7452, -0.7077,  0.9909,
          1.5700,  3.1840, -2.6577, -1.3184, -3.1520,  3.4151, -3.4497,  1.1691,
         -1.7590, -0.6628, -1.3111,  2.5236,  0.7560, -2.2019,  3.4130, -0.2609,
         -2.9739, -1.8178, -1.6589, -1.5318,  0.3276, -2.1050,  2.1928, -1.0282,
         -0.8397, -1.6057, -1.9351,  1.7013,  1.6012,  0.4199,  0.7675, -1.3436,
         -0.9599, -0.9688,  0.9187,  0.1685,  2.1680,  2.0887,  3.5451,  0.2440,
          1.4015, -0.7867,  0.2086,  0.0964,  0.2302,  0.8339, -0.5439,  0.3920,
          1.9223, -4.3259,  0.5084, -2.1813, -2.4570,  1.2097,  1.0857,  1.8440,
         -0.3337, -0.7986,  0.6961, -0.6974,  0.4304,  0.0482, -4.3264, -0.0497,
          1.0504,  1.1921,  1.9215, -0.6916, -2.3776, -2.8329, -0.4682, -2.5819,
         -0.3222, -1.1487, -0.2006, -0.3394,  1.3067,  2.4100, -0.7382,  2.6504,
         -0.6375,  2.7258, -2.6267,  0.6677, -0.0650, -4.7144, -1.3212,  1.6889,
         -3.1839, -0.6813,  2.7392, -0.1573, -1.8775, -1.2944, -3.1705, -1.1550]),
 'img_offers': tensor([-0.6435, -1.9848,  0.5523,  2.7954, -0.3388,  1.1586,  1.2474,  4.1859,
          0.4553,  0.8667,  0.6661, -0.6640,  1.6973,  2.5934, -0.4554,  1.4387,
         -2.8688, -0.2225, -3.0006, -2.9394,  2.2802, -1.9147, -2.1629,  1.8777,
          1.0853,  0.3448,  0.2140, -0.0112,  1.2305,  1.0910,  0.1449, -0.0210,
         -1.6041, -0.6788,  0.2911,  1.8669,  0.3128,  1.9662,  0.1593,  2.1849,
         -2.8682,  1.3189,  2.3367, -0.4194, -0.7240, -2.1912,  2.1554, -1.6714,
         -1.1361,  0.1596, -0.3313,  0.5766,  0.4637, -0.7501,  1.4251, -1.2154,
         -0.0740,  1.6357,  1.9747, -2.1560, -1.0274,  2.5790,  0.2482,  0.9248,
          0.9343, -4.4920,  0.4258,  3.2401,  1.5318,  1.8698,  0.3277, -0.8774,
         -2.5381,  0.4729, -0.7207, -0.7286, -2.7254,  1.2845, -0.4611,  2.4485,
         -1.3046,  0.6756, -0.3077,  0.8797,  0.8158,  0.6263, -0.4351,  0.4936,
          2.7144, -0.2853, -0.1101,  1.0523,  1.3684,  1.4066,  0.7988,  2.1752,
          0.1494, -1.4571,  0.9632,  1.2509,  0.5271,  0.4255, -0.0730, -1.4775,
          0.6841, -2.8353, -0.7290, -2.3002, -0.8857,  0.8457, -1.2650,  1.6214,
          1.0550, -0.2691, -1.0106, -1.9607, -1.0299,  1.6121, -2.5801, -2.6519,
          0.1561, -0.6770,  0.7617, -0.1254, -1.2355,  2.5778, -0.0610,  1.5618,
         -1.4958,  1.9190,  2.9408, -0.8805, -1.9082,  2.4840,  0.2837,  2.8090,
         -1.6586,  1.0424,  0.1585, -1.3927, -3.6186, -0.5051, -0.7197, -1.6169,
          3.7960,  2.0173,  0.1294,  1.1663,  0.2240, -1.0188, -1.8631, -0.4459,
         -1.6867,  1.0626, -1.2353,  2.6937, -1.8205, -2.1765,  0.1948,  0.4264,
          2.3722,  3.1891, -2.9407, -0.2682, -2.4544,  4.5659, -3.2583,  2.4640,
         -0.4349, -0.5278, -0.6819,  2.0222,  0.7898, -3.1871,  3.4773, -0.1050,
         -2.3634, -1.7262, -1.7032, -1.7078,  0.1936, -2.2516,  1.8059, -2.2149,
          1.1609, -0.7498, -0.8401,  2.4598, -0.0701,  0.0587, -0.2129, -2.4231,
         -1.9873, -1.0846,  1.8465,  0.3942,  2.7434,  0.2461,  4.2758,  1.3407,
          0.8418, -0.6839, -0.3220,  0.4706,  0.2591,  0.8219,  0.3444,  0.2470,
          0.7087, -3.7017,  2.0460, -2.8040, -2.9096,  0.9133, -1.1558,  2.0145,
         -2.0555, -0.9456,  0.5584,  0.8531, -1.7674,  1.1421, -3.6922, -0.9541,
          0.6432,  2.2138,  1.9143, -0.6814, -2.0921, -2.1638,  0.4294, -2.9454,
          0.6829, -1.3312, -0.2782,  0.2089,  0.7435,  2.1040, -0.3149,  4.0575,
          0.2851,  3.7817, -0.4440,  0.8747,  0.7568, -4.5514, -0.4381,  1.2163,
         -0.6462,  1.6373,  1.8729,  0.7069, -3.1530, -2.3120, -2.7007,  0.2552]),
 'tittle_goods': tensor([ 0.0278, -0.0688, -0.0165,  0.0398, -0.0129, -0.0181,  0.0758, -0.0453,
         -0.0026, -0.1455,  0.0707,  0.1112, -0.0019,  0.0699,  0.0026,  0.0570,
          0.0721,  0.0687,  0.0242,  0.2122,  0.0079, -0.0005,  0.0810, -0.0462,
          0.0376,  0.0426, -0.0321, -0.1252,  0.1196,  0.0600,  0.1884, -0.0328,
         -0.0376,  0.0625,  0.0829,  0.0144, -0.1533,  0.1490, -0.1689,  0.0242,
         -0.1288,  0.0380, -0.0920, -0.0998,  0.1221, -0.0834,  0.1052, -0.0336,
          0.0177, -0.1118,  0.0051,  0.0833, -0.0020,  0.0375, -0.0118,  0.0186,
         -0.0733, -0.0120,  0.0486, -0.0171,  0.0259, -0.0560, -0.0858,  0.0691],
        dtype=torch.float16),
 'tittle_offers': tensor([ 0.1096,  0.0408,  0.0952, -0.0608, -0.1425,  0.0084,  0.0219,  0.0252,
          0.0088,  0.0413, -0.0039, -0.0883,  0.1091,  0.0314, -0.1108,  0.1017,
         -0.0374,  0.0592, -0.1516,  0.0323, -0.0550,  0.1237, -0.1033, -0.0456,
          0.0063, -0.1024,  0.0342,  0.0801,  0.0692,  0.0574, -0.0790,  0.1311,
         -0.0065,  0.1882,  0.0173, -0.0964,  0.0177,  0.0408,  0.1523,  0.0716,
          0.1023,  0.0302,  0.2002,  0.0435,  0.0454,  0.0146, -0.0630, -0.0112,
         -0.0218, -0.0520,  0.1439, -0.0862,  0.0818, -0.0195,  0.0569, -0.0695,
         -0.0745,  0.0862,  0.0521,  0.0153,  0.0619,  0.0031, -0.0382,  0.0252],
        dtype=torch.float16),
 'difference': tensor(39.),
 'category': 14.0,
 'y': 1}

In [139]:
class myModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.p = nn.Sequential(nn.Linear(256, 128), nn.LayerNorm(128), nn.ReLU())
        self.sc = nn.Sequential(nn.Linear(1, 16), nn.LayerNorm(16))
        self.f = nn.Sequential(nn.Linear(128, 64), nn.LayerNorm(128), nn.ReLU())
        self.to64 = nn.Linear(64*4+16, 64)
        self.relu = nn.ReLU()
        self.f = nn.Linear(128, 64)
        self.ln128 = nn.LayerNorm(128)
        self.layernorm64 = nn.LayerNorm(64)
        self.head = nn.Linear(64, 1)


    def forward(self, i_g, i_o, t_g, t_o, p_d):
        i_g_128 = self.p(i_g)
        i_o_128 = self.p(i_o)
        i_g_64 = self.f(i_g_128)
        i_o_64 = self.f(i_g_128)
        p_d_16 = self.sc(p_d.unsqueeze(0))
        t_g_64 = t_g
        t_o_64 = t_o
        x = torch.cat([i_g_64, i_o_64, t_g_64, t_o_64 ,p_d_16], dim=-1)
        x = self.to64(x)
        x = self.relu(x)
        x = self.layernorm64(x)
        itg = self.head(x)

        return itg.squeeze(-1)

In [140]:
model = myModel()

In [142]:
d = dataset[0]

In [143]:
print(d['tittle_goods'].dim())
print(d['img_goods'].dim())
print(d['difference'].dim())

1
1
0

In [128]:
len(d['img_goods'])

256

In [129]:
z = torch.cat([d['tittle_goods'], d['tittle_offers']], dim=-1)
z

tensor([ 0.0331, -0.0389, -0.0673,  0.0877, -0.1101,  0.0640,  0.0875,  0.0638,
        -0.0395,  0.0329, -0.0607, -0.0452,  0.0022, -0.0978,  0.0819, -0.1081,
         0.1948,  0.1021, -0.0332, -0.0078, -0.0195, -0.0535,  0.0536,  0.0163,
         0.0802,  0.1094, -0.0042, -0.0624,  0.0054, -0.0735, -0.1730, -0.0931,
        -0.0831,  0.0831, -0.0836,  0.0087,  0.0966, -0.0715, -0.1781, -0.0016,
         0.0426,  0.0326, -0.0892, -0.0171,  0.0079,  0.0879,  0.0014,  0.0949,
         0.0138,  0.0974,  0.0372, -0.0817,  0.0505, -0.1765, -0.1270, -0.0375,
        -0.0168,  0.0430,  0.0841, -0.1094, -0.0133, -0.0390,  0.0239,  0.1465,
         0.0168,  0.1666, -0.0356, -0.0580,  0.0037, -0.0450,  0.0459, -0.0033,
        -0.0759,  0.0774,  0.0372,  0.0220,  0.0288,  0.0289, -0.0124,  0.2080,
        -0.0809,  0.1547,  0.0771,  0.0277,  0.2278, -0.0572, -0.0476, -0.0018,
        -0.1110,  0.0115, -0.0196, -0.0759, -0.0135,  0.0615,  0.0905, -0.0010,
         0.0518,  0.0072,  0.0024,  0.0621,  0.0690,  0.1656, -0.0601,  0.0852,
        -0.1675, -0.0249,  0.0874, -0.0825, -0.0516, -0.1147,  0.1216,  0.0605,
         0.0409, -0.0184,  0.0753,  0.0877, -0.0128,  0.0321, -0.0313, -0.0984,
        -0.0585, -0.0147,  0.0375,  0.0447, -0.0837,  0.0385,  0.0565, -0.1306],
       dtype=torch.float16)

In [144]:
logits = model(d['img_goods'], d['img_offers'], d['tittle_goods'], d['tittle_offers'], d['difference'])

In [145]:
logits

tensor(1.2361, grad_fn=<SqueezeBackward1>)